name: "Jekyll true minimal theme"
description: "Lightweight theme"

url: 'https://cyevgeniy.github.io/jekyll-true-minimal' 

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 2
paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site
gems: ['jekyll-paginate']

sass:
    style: :compressed
    sass_dir: assets/css/

